[WIP] DMPL
abgfbr/mis-builder pull request #3
Opened 2019-03-27 13:21 UTC by mileo

CC: @sadamo

2019-04-10 03:11 UTC, mileo commented
Depends of https://github.com/OCA/web/pull/1242

2019-04-10 20:26 UTC, hendrixcosta requested changes

2019-04-10 20:26 UTC, hendrixcosta commented on mis_builder/views/mis_builder.xml
> -                <sheet>
Tem uma linha da localização que depende desse cara.
```
Detalhes do Erro:
Elemento '<sheet>' não pode ser localizado na visão pai

Contexto de erro:
Veja `mis.report.instance.view.form (in l10n_br_contabilidade)`
[view_id: 2304, xml_id: l10n_br_contabilidade.mis_report_instance_view_form, model: mis.report.instance, parent_id: 2257]" while parsing /opt/odoo/parts/addons/l10n-brazil/l10n_br_contabilidade/views/mis_report_instance.xml:8, near
<record model="ir.ui.view" id="mis_report_instance_view_form">
        <field name="name">mis.report.instance.view.form (in l10n_br_contabilidade)</field>
        <field name="model">mis.report.instance</field>
        <field name="inherit_id" ref="mis_builder.mis_report_instance_view_form"/>
        <field name="arch" type="xml">
            <data><field name="target_move" position="after">
                <newline/>
                <field name="accountant_id" colspan="4"/>
                <field name="administrator_id" colspan="4"/>
                <field name="considerations" colspan="4"/>
            </field>
            <sheet position="inside">
                <group>
                    <field name="attachment_ids" widget="many2many_binary"/>
                </group>
            </sheet>
        </data></field>
    </record>
```

2019-04-10 20:28 UTC, hendrixcosta commented
Aproveitando para lembrar das traduções 
![image](https://user-images.githubusercontent.com/7250580/55910947-fe969380-5bb5-11e9-8d51-4dff9ff3ea75.png)

2019-04-10 20:30 UTC, hendrixcosta commented
Como melhoria de usabilidade, a page de layout poderia ser a última já que depende do preenchimento da page de períodos e de KPIs

![image](https://user-images.githubusercontent.com/7250580/55911099-533a0e80-5bb6-11e9-83e4-c4da72a0cce7.png)

2019-04-11 11:18 UTC, mileo commented
@hendrixcosta correções efetuadas

2019-04-12 12:02 UTC, hendrixcosta requested changes
Faltando permissão para mis.report.period

2019-04-12 12:03 UTC, hendrixcosta requested changes
Esse modelo também falta permissão: mis.report.position

2019-04-15 18:47 UTC, hendrixcosta approved these changes

2019-04-15 18:48 UTC, lfdivino approved these changes

2019-04-15 18:49 UTC, merged